#! /usr/bin/env python
from  RMextract.LOFAR_TOOLS.createRMParmdb import createRMParmdb
import sys
import os

if __name__ == "__main__":
    import argparse

    descriptiontext = "Create a parmDB with the Ionospheric RM predicted from data in IONEX files.\n"
    parser = argparse.ArgumentParser(description=descriptiontext)
   
    parser.add_argument('MS',help='Measurement-Set for which the parmDB is to be created.')
    parser.add_argument('-o','--out', help='name of the parmdb',dest="parmdbName",default='RMParmdb');
    parser.add_argument('-p','--patch', help='name of the patch or source for which to create the values',dest="patch",default="phase_center")
    #parser.add_argument('-s','--sky', help='name of the skymodel, if no source/patch name is given first will be selected. If you do not set the skymodel, the phasecenter of the MS will be assumed as your direction. If option --use_phase_center is used the direction in the sky model are ignored. However, it could still be useful to automatically select a patch name, which is needed for direction dependent parmareters.',dest="sky")
    #parser.add_argument('-f','--use_phase_center', help='force using of phase center of MS, even if skymodel is supplied',action='store_true',dest="usePhaseCenter");
    parser.add_argument('--IONprefix', help='prefix of IONEX files, either CODG or ROBR',dest="prefix",default='CODG');
    parser.add_argument('--IONserver', help='server of IONEX files',dest="server",default='ftp://ftp.unibe.ch/aiub/CODE/')
    parser.add_argument('--IONpath', help='location of IONEX files',dest="ionexPath",default='./')
    parser.add_argument('--all','-a', help='calculate RM per station (default calculates only for CS002LBA)',action='store_true',dest="allStations")
    parser.add_argument('-t','--timestep', help='timestep in seconds. for values <=0 (default) the timegrid of the MS is used ',dest="timestep",type=float,default=900.)
    parser.add_argument('-e','--smart_interpol', help='float parameter describing how much of earth rotation is taken in to account in interpolation of the IONEX files. 1.0 means time interpolation assumes ionosphere rotates in opposite direction of the Earth. 0.0 (default) means no rotation applied',dest="earth_rot",type=float,default=0)
    parser.add_argument('-r','--overwrite',help='overwrite existing parmdb',action='store_true',dest="overwrite")

    args = parser.parse_args()
        
    stat_names=None
    if args.allStations:
        stat_names='all'
    if not args.overwrite and not os.path.isdir(args.parmdbName):
        args.overwrite=True
        
    createRMParmdb(args.MS,
                   parmdbname=args.parmdbName,
                   create=args.overwrite,
                   patchname=args.patch,
                   server=args.server,
                   prefix=args.prefix,
                   ionexPath=args.ionexPath,
                   earth_rot=args.earth_rot,
                   timestep=args.timestep,
                   stat_names=stat_names)
    
