#! /usr/bin/env python
from  RMextract.LOFAR_TOOLS.createRMParmdb import createRMParmdb
from optparse import OptionParser;
import sys
import os
parser = OptionParser();

parser.add_option('-o','--out', help='name of the parmdb',dest="parmdbName",default='RMParmdb');
parser.add_option('-p','--patch', help='name of the patch or source for which to create the values',dest="patch",default="phase_center")
#parser.add_option('-s','--sky', help='name of the skymodel, if no source/patch name is given first will be selected. If you do not set the skymodel, the phasecenter of the MS will be assumed as your direction. If option --use_phase_center is used the direction in the sky model are ignored. However, it could still be useful to automatically select a patch name, which is needed for direction dependent parmareters.',dest="sky")
#parser.add_option('-f','--use_phase_center', help='force using of phase center of MS, even if skymodel is supplied',action='store_true',dest="usePhaseCenter");
parser.add_option('--IONprefix', help='prefix of IONEX files, either CODG or ROBR',dest="prefix",default='CODG');
parser.add_option('--IONserver', help='server of IONEX files',dest="server",default='ftp://ftp.unibe.ch/aiub/CODE/')
parser.add_option('--IONpath', help='location of IONEX files',dest="ionexPath",default='./')
parser.add_option('--all','-a', help='calculate RM per station (default calculates only for CS002LBA)',action='store_true',dest="allStations")
parser.add_option('-t','--timestep', help='timestep in seconds. for values <=0 (default) the timegrid of the MS is used ',dest="timestep",type="float",default=900.)
parser.add_option('-e','--smart_interpol', help='float parameter describing how much of earth rotation is taken in to account in interpolation of the IONEX files. 1.0 means time interpolation assumes ionosphere rotates in opposite direction of the Earth. 0.0 (default) means no rotation applied',dest="earth_rot",type="float",default=0)
parser.add_option('-r','--overwrite',help='overwrite existing parmdb',action='store_true',dest="overwrite")


def main(argv):  
    if len(argv)<1:
        print "usage: createRMParmdb <MS> <options>, createRMParmdb -h tosee list of options"
        return
    if argv[0]=="-h":
        (options, args) =parser.parse_args(argv[:])
    else:
        (options, args) =parser.parse_args(argv[1:])
        
    MS=argv[0]
    stat_names=None
    if options.allStations:
        stat_names='all'
    if not options.overwrite and not os.path.isdir(options.parmdbName):
        options.overwrite=True
        
    createRMParmdb(MS,parmdbname=options.parmdbName,
                   create=options.overwrite,
                   patchname=options.patch,
                   server=options.server,
                   prefix=options.prefix,
                   ionexPath=options.ionexPath,
                   earth_rot=options.earth_rot,
                   timestep=options.timestep,
                   stat_names=stat_names)


if __name__ == "__main__":
    main(sys.argv[1:])
