C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pyinitblock7(setupfunc)
      external setupfunc
      real d1
      real xkk
      real fp30
      real fp3u
      real fp1
      real fp2
      common /block7/ d1,xkk,fp30,fp3u,fp1,fp2
      call setupfunc(d1,xkk,fp30,fp3u,fp1,fp2)
      end

      subroutine f2pyinitblock6(setupfunc)
      external setupfunc
      real hmd
      real nmd
      real hdx
      common /block6/ hmd,nmd,hdx
      call setupfunc(hmd,nmd,hdx)
      end

      subroutine f2pyinitblock5(setupfunc)
      external setupfunc
      logical enight
      real e(4)
      common /block5/ enight,e
      call setupfunc(enight,e)
      end

      subroutine f2pyinitblock4(setupfunc)
      external setupfunc
      real hme
      real nme
      real hef
      common /block4/ hme,nme,hef
      call setupfunc(hme,nme,hef)
      end

      subroutine f2pyinitconst(setupfunc)
      external setupfunc
      real umr
      real pi
      common /const/ umr,pi
      call setupfunc(umr,pi)
      end

      subroutine f2pyinitblock2(setupfunc)
      external setupfunc
      real b0
      real b1
      real c1
      common /block2/ b0,b1,c1
      call setupfunc(b0,b1,c1)
      end

      subroutine f2pyinitblock1(setupfunc)
      external setupfunc
      real hmf2
      real nmf2
      real hmf1
      logical f1reg
      common /block1/ hmf2,nmf2,hmf1,f1reg
      call setupfunc(hmf2,nmf2,hmf1,f1reg)
      end

      subroutine f2pyinitigrf1(setupfunc)
      external setupfunc
      real era
      real aquad
      real bquad
      real dimo
      common /igrf1/ era,aquad,bquad,dimo
      call setupfunc(era,aquad,bquad,dimo)
      end

      subroutine f2pyinitblock8(setupfunc)
      external setupfunc
      real hs
      real tnhs
      real xsm(4)
      real mm(5)
      real dti(4)
      integer mxsm
      common /block8/ hs,tnhs,xsm,mm,dti,mxsm
      call setupfunc(hs,tnhs,xsm,mm,dti,mxsm)
      end

      subroutine f2pyinitargexp(setupfunc)
      external setupfunc
      real argmax
      common /argexp/ argmax
      call setupfunc(argmax)
      end

      subroutine f2pyinitiounit(setupfunc)
      external setupfunc
      integer konsol
      logical mess
      common /iounit/ konsol,mess
      call setupfunc(konsol,mess)
      end

      subroutine f2pyinitblo11(setupfunc)
      external setupfunc
      real b2top
      real tc3
      integer itopn
      real alg10
      real hcor1
      common /blo11/ b2top,tc3,itopn,alg10,hcor1
      call setupfunc(b2top,tc3,itopn,alg10,hcor1)
      end

      subroutine f2pyinitblo10(setupfunc)
      external setupfunc
      real beta
      real eta
      real delta
      real zeta
      common /blo10/ beta,eta,delta,zeta
      call setupfunc(beta,eta,delta,zeta)
      end

      subroutine f2pyinitconst1(setupfunc)
      external setupfunc
      real humr
      real dumr
      common /const1/ humr,dumr
      call setupfunc(humr,dumr)
      end

      subroutine f2pyinitblote(setupfunc)
      external setupfunc
      real ahh(7)
      real ate1
      real stte(6)
      real dte(5)
      common /blote/ ahh,ate1,stte,dte
      call setupfunc(ahh,ate1,stte,dte)
      end

      subroutine f2pyinitblock3(setupfunc)
      external setupfunc
      real hz
      real t
      real hst
      common /block3/ hz,t,hst
      call setupfunc(hz,t,hst)
      end

      subroutine f2pyinitcsw(setupfunc)
      external setupfunc
      real sw(25)
      integer isw
      real swc(25)
      common /csw/ sw,isw,swc
      call setupfunc(sw,isw,swc)
      end

      subroutine f2pyinitfindrlat(setupfunc)
      external setupfunc
      real flon
      real ryear
      common /findrlat/ flon,ryear
      call setupfunc(flon,ryear)
      end

      subroutine f2pyinitqtop(setupfunc)
      external setupfunc
      real y05
      real h05top
      real qf
      real xnetop
      real xm3000
      real hhalf
      real tau
      common /qtop/ y05,h05top,qf,xnetop,xm3000,hhalf,tau
      call setupfunc(y05,h05top,qf,xnetop,xm3000,hhalf,tau)
      end

      subroutine f2pyinitfircom(setupfunc)
      external setupfunc
      real eden(81,5,12,12,3)
      real tabhe(81)
      real tabla(5)
      real tabmo(12)
      real tabza(12)
      real tabfl(3)
      common /fircom/ eden,tabhe,tabla,tabmo,tabza,tabfl
      call setupfunc(eden,tabhe,tabla,tabmo,tabza,tabfl)
      end

      subroutine f2pyinitparm7(setupfunc)
      external setupfunc
      real pt1(50)
      real pt2(50)
      real pt3(50)
      real pa1(50)
      real pa2(50)
      real pa3(50)
      real pb1(50)
      real pb2(50)
      real pb3(50)
      real pc1(50)
      real pc2(50)
      real pc3(50)
      real pd1(50)
      real pd2(50)
      real pd3(50)
      real pe1(50)
      real pe2(50)
      real pe3(50)
      real pf1(50)
      real pf2(50)
      real pf3(50)
      real pg1(50)
      real pg2(50)
      real pg3(50)
      real ph1(50)
      real ph2(50)
      real ph3(50)
      real pi1(50)
      real pi2(50)
      real pi3(50)
      real pj1(50)
      real pj2(50)
      real pj3(50)
      real pk1(50)
      real pl1(50)
      real pl2(50)
      real pm1(50)
      real pm2(50)
      real pn1(50)
      real pn2(50)
      real po1(50)
      real po2(50)
      real pp1(50)
      real pp2(50)
      real pq1(50)
      real pq2(50)
      real pr1(50)
      real pr2(50)
      real ps1(50)
      real ps2(50)
      real pu1(50)
      real pu2(50)
      real pv1(50)
      real pv2(50)
      real pw1(50)
      real pw2(50)
      real px1(50)
      real px2(50)
      real py1(50)
      real py2(50)
      real pz1(50)
      real pz2(50)
      real paa1(50)
      real paa2(50)
      common /parm7/ pt1,pt2,pt3,pa1,pa2,pa3,pb1,pb2,pb3,pc1,pc2,p
     &c3,pd1,pd2,pd3,pe1,pe2,pe3,pf1,pf2,pf3,pg1,pg2,pg3,ph1,ph2,ph3,pi1
     &,pi2,pi3,pj1,pj2,pj3,pk1,pl1,pl2,pm1,pm2,pn1,pn2,po1,po2,pp1,pp2,p
     &q1,pq2,pr1,pr2,ps1,ps2,pu1,pu2,pv1,pv2,pw1,pw2,px1,px2,py1,py2,pz1
     &,pz2,paa1,paa2
      call setupfunc(pt1,pt2,pt3,pa1,pa2,pa3,pb1,pb2,pb3,pc1,pc2,p
     &c3,pd1,pd2,pd3,pe1,pe2,pe3,pf1,pf2,pf3,pg1,pg2,pg3,ph1,ph2,ph3,pi1
     &,pi2,pi3,pj1,pj2,pj3,pk1,pl1,pl2,pm1,pm2,pn1,pn2,po1,po2,pp1,pp2,p
     &q1,pq2,pr1,pr2,ps1,ps2,pu1,pu2,pv1,pv2,pw1,pw2,px1,px2,py1,py2,pz1
     &,pz2,paa1,paa2)
      end

      subroutine f2pyinitlower7(setupfunc)
      external setupfunc
      real ptm(10)
      real pdm(10,8)
      common /lower7/ ptm,pdm
      call setupfunc(ptm,pdm)
      end

      subroutine f2pyinitmavg7(setupfunc)
      external setupfunc
      real pavgm(10)
      common /mavg7/ pavgm
      call setupfunc(pavgm)
      end

      subroutine f2pyinitmetsel(setupfunc)
      external setupfunc
      integer imr
      common /metsel/ imr
      call setupfunc(imr)
      end

      subroutine f2pyinitdatim7(setupfunc)
      external setupfunc
      character isdate(3,4)
      character istime(2,4)
      character name(2,4)
      common /datim7/ isdate,istime,name
      call setupfunc(isdate,istime,name)
      end

      subroutine f2pyinitBLOCK7(setupfunc)
      external setupfunc
      real D1
      real XKK
      real FP30
      real FP3U
      real FP1
      real FP2
      common /BLOCK7/ D1,XKK,FP30,FP3U,FP1,FP2
      call setupfunc(D1,XKK,FP30,FP3U,FP1,FP2)
      end

      subroutine f2pyinitBLOCK6(setupfunc)
      external setupfunc
      real HMD
      real NMD
      real HDX
      common /BLOCK6/ HMD,NMD,HDX
      call setupfunc(HMD,NMD,HDX)
      end

      subroutine f2pyinitBLOCK5(setupfunc)
      external setupfunc
      real ENIGHT
      real E(4)
      common /BLOCK5/ ENIGHT,E
      call setupfunc(ENIGHT,E)
      end

      subroutine f2pyinitBLOCK4(setupfunc)
      external setupfunc
      real HME
      real NME
      real HEF
      common /BLOCK4/ HME,NME,HEF
      call setupfunc(HME,NME,HEF)
      end

      subroutine f2pyinitCONST(setupfunc)
      external setupfunc
      real UMR
      real PI
      common /CONST/ UMR,PI
      call setupfunc(UMR,PI)
      end

      subroutine f2pyinitBLOCK2(setupfunc)
      external setupfunc
      real B0
      real B1
      real C1
      common /BLOCK2/ B0,B1,C1
      call setupfunc(B0,B1,C1)
      end

      subroutine f2pyinitBLOCK1(setupfunc)
      external setupfunc
      real HMF2
      real NMF2
      real HMF1
      logical F1REG
      common /BLOCK1/ HMF2,NMF2,HMF1,F1REG
      call setupfunc(HMF2,NMF2,HMF1,F1REG)
      end

      subroutine f2pyinitIGRF1(setupfunc)
      external setupfunc
      real ERA
      real AQUAD
      real BQUAD
      real DIMO
      common /IGRF1/ ERA,AQUAD,BQUAD,DIMO
      call setupfunc(ERA,AQUAD,BQUAD,DIMO)
      end

      subroutine f2pyinitARGEXP(setupfunc)
      external setupfunc
      real ARGMAX
      common /ARGEXP/ ARGMAX
      call setupfunc(ARGMAX)
      end

      subroutine f2pyinitBLO11(setupfunc)
      external setupfunc
      real B2TOP
      real TC3
      integer itopn
      real alg10
      real hcor1
      common /BLO11/ B2TOP,TC3,itopn,alg10,hcor1
      call setupfunc(B2TOP,TC3,itopn,alg10,hcor1)
      end

      subroutine f2pyinitBLO10(setupfunc)
      external setupfunc
      real BETA
      real ETA
      real DELTA
      real ZETA
      common /BLO10/ BETA,ETA,DELTA,ZETA
      call setupfunc(BETA,ETA,DELTA,ZETA)
      end

      subroutine f2pyinitBLOTE(setupfunc)
      external setupfunc
      real AHH(7)
      real ATE1
      real STTE(6)
      real DTE(5)
      common /BLOTE/ AHH,ATE1,STTE,DTE
      call setupfunc(AHH,ATE1,STTE,DTE)
      end

      subroutine f2pyinitfindRLAT(setupfunc)
      external setupfunc
      real FLON
      real RYEAR
      common /findRLAT/ FLON,RYEAR
      call setupfunc(FLON,RYEAR)
      end

      subroutine f2pyinitBLOCK3(setupfunc)
      external setupfunc
      real HZ
      real T
      real HST
      common /BLOCK3/ HZ,T,HST
      call setupfunc(HZ,T,HST)
      end

      subroutine f2pyinitCSW(setupfunc)
      external setupfunc
      real SW(25)
      integer ISW
      real SWC(25)
      common /CSW/ SW,ISW,SWC
      call setupfunc(SW,ISW,SWC)
      end

      subroutine f2pyinitBLOCK8(setupfunc)
      external setupfunc
      real HS
      real TNHS
      real XSM(4)
      real MM(5)
      real DTI(4)
      integer MXSM
      common /BLOCK8/ HS,TNHS,XSM,MM,DTI,MXSM
      call setupfunc(HS,TNHS,XSM,MM,DTI,MXSM)
      end

      subroutine f2pyinitQTOP(setupfunc)
      external setupfunc
      real Y05
      real H05TOP
      real QF
      real XNETOP
      real XM3000
      real HHALF
      real TAU
      common /QTOP/ Y05,H05TOP,QF,XNETOP,XM3000,HHALF,TAU
      call setupfunc(Y05,H05TOP,QF,XNETOP,XM3000,HHALF,TAU)
      end

      subroutine f2pyinitAMTB(setupfunc)
      external setupfunc
      real BINT(9,9,5)
      real BEXT(9,9,5)
      real RE
      real TZERO
      integer IFIT
      integer IB
      integer KINT
      integer LINT
      integer KEXT
      integer LEXT
      integer KMAX
      real FN(9,9)
      common /AMTB/ BINT,BEXT,RE,TZERO,IFIT,IB,KINT,LINT,KEXT,LEXT
     &,KMAX,FN
      call setupfunc(BINT,BEXT,RE,TZERO,IFIT,IB,KINT,LINT,KEXT,LEX
     &T,KMAX,FN)
      end

      subroutine f2pyinithmF2UT(setupfunc)
      external setupfunc
      double precision hmF2_UT(24)
      common /hmF2UT/ hmF2_UT
      call setupfunc(hmF2_UT)
      end

      subroutine f2pyinitconstt(setupfunc)
      external setupfunc
      double precision umr
      common /constt/ umr
      call setupfunc(umr)
      end

      subroutine f2pyinitradUT(setupfunc)
      external setupfunc
      double precision dtr
      common /radUT/ dtr
      call setupfunc(dtr)
      end

      subroutine f2pyinitATB(setupfunc)
      external setupfunc
      real BINT(7,7,5)
      real BEXT(7,7,5)
      real RE
      real TZERO
      integer IFIT
      integer IB
      integer KINT
      integer LINT
      integer KEXT
      integer LEXT
      integer KMAX
      real FN(7,7)
      common /ATB/ BINT,BEXT,RE,TZERO,IFIT,IB,KINT,LINT,KEXT,LEXT,
     &KMAX,FN
      call setupfunc(BINT,BEXT,RE,TZERO,IFIT,IB,KINT,LINT,KEXT,LEX
     &T,KMAX,FN)
      end

      subroutine f2pyinitigrz(setupfunc)
      external setupfunc
      real aig(806)
      real arz(806)
      integer iymst
      integer iymend
      common /igrz/ aig,arz,iymst,iymend
      call setupfunc(aig,arz,iymst,iymend)
      end

      subroutine f2pyinitapfa(setupfunc)
      external setupfunc
      integer aap(23000,9)
      real af107(23000,3)
      integer n
      common /apfa/ aap,af107,n
      call setupfunc(aap,af107,n)
      end

      subroutine f2pyinitmflux(setupfunc)
      external setupfunc
      integer kf
      integer n
      common /mflux/ kf,n
      call setupfunc(kf,n)
      end

      subroutine f2pyinitFIRCOM(setupfunc)
      external setupfunc
      real EDEN(81,5,12,12,3)
      real TABHE(81)
      real TABLA(5)
      real TABMO(12)
      real TABZA(12)
      real TABFL(3)
      common /FIRCOM/ EDEN,TABHE,TABLA,TABMO,TABZA,TABFL
      call setupfunc(EDEN,TABHE,TABLA,TABMO,TABZA,TABFL)
      end

      subroutine f2pyinitFIDB0(setupfunc)
      external setupfunc
      real SP(3)
      common /FIDB0/ SP
      call setupfunc(SP)
      end

      subroutine f2pyinitIGRF2(setupfunc)
      external setupfunc
      real X(3)
      real H(196)
      common /IGRF2/ X,H
      call setupfunc(X,H)
      end

      subroutine f2pyinitMODEL(setupfunc)
      external setupfunc
      integer NMAX
      real TIME
      real G(196)
      character*13 NAME
      common /MODEL/ NMAX,TIME,G,NAME
      call setupfunc(NMAX,TIME,G,NAME)
      end

      subroutine f2pyinitDIPOL(setupfunc)
      external setupfunc
      real GHI1
      real GHI2
      real GHI3
      common /DIPOL/ GHI1,GHI2,GHI3
      call setupfunc(GHI1,GHI2,GHI3)
      end

      subroutine f2pyinitNM(setupfunc)
      external setupfunc
      integer NM
      common /NM/ NM
      call setupfunc(NM)
      end

      subroutine f2pyinitIYR(setupfunc)
      external setupfunc
      integer IYR
      common /IYR/ IYR
      call setupfunc(IYR)
      end

      subroutine f2pyinitcgmgeo(setupfunc)
      external setupfunc
      real clat
      logical cr360
      logical cr0
      real rh
      common /cgmgeo/ clat,cr360,cr0,rh
      call setupfunc(clat,cr360,cr0,rh)
      end

      subroutine f2pyinitA5(setupfunc)
      external setupfunc
      real DS3
      common /A5/ DS3
      call setupfunc(DS3)
      end

      subroutine f2pyinitC1(setupfunc)
      external setupfunc
      real ST0
      real CT0
      real SL0
      real CL0
      real CTCL
      real STCL
      real CTSL
      real STSL
      real SFI
      real CFI
      real SPS
      real CPS
      real SHI
      real CHI
      real HI
      real PSI
      real XMUT
      real A11
      real A21
      real A31
      real A12
      real A22
      real A32
      real A13
      real A23
      real A33
      real DS3
      integer K
      integer IY
      real BA(8)
      common /C1/ ST0,CT0,SL0,CL0,CTCL,STCL,CTSL,STSL,SFI,CFI,SPS,
     &CPS,SHI,CHI,HI,PSI,XMUT,A11,A21,A31,A12,A22,A32,A13,A23,A33,DS3,K,
     &IY,BA
      call setupfunc(ST0,CT0,SL0,CL0,CTCL,STCL,CTSL,STSL,SFI,CFI,S
     &PS,CPS,SHI,CHI,HI,PSI,XMUT,A11,A21,A31,A12,A22,A32,A13,A23,A33,DS3
     &,K,IY,BA)
      end

      subroutine f2pyinitMESO7(setupfunc)
      external setupfunc
      real TN1(5)
      real TN2(4)
      real TN3(5)
      real TGN1(2)
      real TGN2(2)
      real TGN3(2)
      common /MESO7/ TN1,TN2,TN3,TGN1,TGN2,TGN3
      call setupfunc(TN1,TN2,TN3,TGN1,TGN2,TGN3)
      end

      subroutine f2pyinitLOWER7(setupfunc)
      external setupfunc
      real PTM(10)
      real PDM(10,8)
      common /LOWER7/ PTM,PDM
      call setupfunc(PTM,PDM)
      end

      subroutine f2pyinitDATIM7(setupfunc)
      external setupfunc
      character ISD(3,4)
      character IST(2,4)
      character NAM(2,4)
      common /DATIM7/ ISD,IST,NAM
      call setupfunc(ISD,IST,NAM)
      end

      subroutine f2pyinitDMIX(setupfunc)
      external setupfunc
      real DM04
      real DM16
      real DM28
      real DM32
      real DM40
      real DM01
      real DM14
      common /DMIX/ DM04,DM16,DM28,DM32,DM40,DM01,DM14
      call setupfunc(DM04,DM16,DM28,DM32,DM40,DM01,DM14)
      end

      subroutine f2pyinitGTS3C(setupfunc)
      external setupfunc
      real TLB
      real S
      real DB04
      real DB16
      real DB28
      real DB32
      real DB40
      real DB48
      real DB01
      real ZA
      real T0
      real Z0
      real G0
      real RL
      real DD
      real DB14
      real TR12
      common /GTS3C/ TLB,S,DB04,DB16,DB28,DB32,DB40,DB48,DB01,ZA,T
     &0,Z0,G0,RL,DD,DB14,TR12
      call setupfunc(TLB,S,DB04,DB16,DB28,DB32,DB40,DB48,DB01,ZA,T
     &0,Z0,G0,RL,DD,DB14,TR12)
      end

      subroutine f2pyinitMAVG7(setupfunc)
      external setupfunc
      real PAVGM(10)
      common /MAVG7/ PAVGM
      call setupfunc(PAVGM)
      end

      subroutine f2pyinitDATIME(setupfunc)
      external setupfunc
      character ISDATE(3,4)
      character ISTIME(2,4)
      character NAME(2,4)
      common /DATIME/ ISDATE,ISTIME,NAME
      call setupfunc(ISDATE,ISTIME,NAME)
      end

      subroutine f2pyinitPARM7(setupfunc)
      external setupfunc
      real PT(150)
      real PDA1(150)
      real PDA2(150)
      real PDA3(150)
      real PDA4(150)
      real PDA5(150)
      real PDA6(150)
      real PDA7(150)
      real PDA8(150)
      real PDA9(150)
      real PS(150)
      real PDL(25,2)
      real PTL(100,4)
      real PMA(100,10)
      real SAM(100)
      common /PARM7/ PT,PDA1,PDA2,PDA3,PDA4,PDA5,PDA6,PDA7,PDA8,PD
     &A9,PS,PDL,PTL,PMA,SAM
      call setupfunc(PT,PDA1,PDA2,PDA3,PDA4,PDA5,PDA6,PDA7,PDA8,PD
     &A9,PS,PDL,PTL,PMA,SAM)
      end

      subroutine f2pyinitMETSEL(setupfunc)
      external setupfunc
      integer IMR
      common /METSEL/ IMR
      call setupfunc(IMR)
      end

      subroutine f2pyinitPARMB(setupfunc)
      external setupfunc
      real GSURF
      real RE
      common /PARMB/ GSURF,RE
      call setupfunc(GSURF,RE)
      end

      subroutine f2pyinitTTEST(setupfunc)
      external setupfunc
      real TINFG
      real GB
      real ROUT
      real TT(15)
      common /TTEST/ TINFG,GB,ROUT,TT
      call setupfunc(TINFG,GB,ROUT,TT)
      end

      subroutine f2pyinitLPOLY(setupfunc)
      external setupfunc
      real PLG(9,4)
      real CTLOC
      real STLOC
      real C2TLOC
      real S2TLOC
      real C3TLOC
      real S3TLOC
      integer IYR
      real DAY
      real DF
      real DFA
      real APD
      real APDF
      real APT(4)
      real XLONG
      common /LPOLY/ PLG,CTLOC,STLOC,C2TLOC,S2TLOC,C3TLOC,S3TLOC,I
     &YR,DAY,DF,DFA,APD,APDF,APT,XLONG
      call setupfunc(PLG,CTLOC,STLOC,C2TLOC,S2TLOC,C3TLOC,S3TLOC,I
     &YR,DAY,DF,DFA,APD,APDF,APT,XLONG)
      end

      subroutine f2pyinitLSQV(setupfunc)
      external setupfunc
      integer MP
      integer II
      integer JG
      integer LT
      real QPB(50)
      integer IERR
      integer IFUN
      integer N
      integer J
      real DV(60)
      common /LSQV/ MP,II,JG,LT,QPB,IERR,IFUN,N,J,DV
      call setupfunc(MP,II,JG,LT,QPB,IERR,IFUN,N,J,DV)
      end

      subroutine f2pyinitFIT(setupfunc)
      external setupfunc
      real TAF
      common /FIT/ TAF
      call setupfunc(TAF)
      end

      subroutine f2pyinitEUVPRD(setupfunc)
      external setupfunc
      real EUVION(3,12)
      real PEXCIT(3,12)
      real PEPION(3,12)
      real OTHPR1(6)
      real OTHPR2(6)
      common /EUVPRD/ EUVION,PEXCIT,PEPION,OTHPR1,OTHPR2
      call setupfunc(EUVION,PEXCIT,PEPION,OTHPR1,OTHPR2)
      end

      subroutine f2pyinitSOL(setupfunc)
      external setupfunc
      real UVFAC(59)
      real EUV
      common /SOL/ UVFAC,EUV
      call setupfunc(UVFAC,EUV)
      end

      subroutine f2pyinitSIGS(setupfunc)
      external setupfunc
      real ZFLUX(37)
      real SIGABS(3,37)
      real ZLAM(37)
      real SIGION(3,37)
      real TPOT(3,10)
      integer NNI(3)
      real LAMAX
      common /SIGS/ ZFLUX,SIGABS,ZLAM,SIGION,TPOT,NNI,LAMAX
      call setupfunc(ZFLUX,SIGABS,ZLAM,SIGION,TPOT,NNI,LAMAX)
      end


